"""Added color labels for hobby

Revision ID: 239f875efe66
Revises: bd48fe47a1db
Create Date: 2020-10-21 16:51:39.504232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239f875efe66'
down_revision = 'bd48fe47a1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=3), default="Red"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
