"""Convert days-hobbies rel table to a Model

Revision ID: 2c94e02de386
Revises: bf4253f03eec
Create Date: 2020-08-23 19:57:15.898010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c94e02de386'
down_revision = 'bf4253f03eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_hobbies_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobby.id'], ),
    sa.PrimaryKeyConstraint('id', 'day_id', 'hobby_id')
    )
    op.drop_table('days')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('day_id', sa.INTEGER(), nullable=False),
    sa.Column('hobby_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobby.id'], ),
    sa.PrimaryKeyConstraint('day_id', 'hobby_id')
    )
    op.drop_table('days_hobbies_table')
    # ### end Alembic commands ###
