"""Fix relationships for hobbby and days

Revision ID: a4695aef3786
Revises: 98ec74833836
Create Date: 2020-08-13 21:58:00.458232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4695aef3786'
down_revision = '98ec74833836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobby.id'], ),
    sa.PrimaryKeyConstraint('day_id', 'hobby_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days')
    # ### end Alembic commands ###
