"""Removed Hobby.Frequency, added Hobby.DaysofWeek

Revision ID: b59aebe955ee
Revises: cb045fcd681c
Create Date: 2020-04-23 13:01:11.478580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59aebe955ee'
down_revision = 'cb045fcd681c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('monday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('saturday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sunday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('thursday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tuesday', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('wednesday', sa.Boolean(), nullable=True))
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.VARCHAR(length=1), nullable=False))
        batch_op.drop_column('wednesday')
        batch_op.drop_column('tuesday')
        batch_op.drop_column('thursday')
        batch_op.drop_column('sunday')
        batch_op.drop_column('saturday')
        batch_op.drop_column('monday')
        batch_op.drop_column('friday')

    # ### end Alembic commands ###
