"""removed link column from hobby

Revision ID: cb045fcd681c
Revises: e841d2e08fea
Create Date: 2020-04-16 10:16:29.547274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb045fcd681c'
down_revision = 'e841d2e08fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
