"""add one-to-many rel for hobby-user

Revision ID: e841d2e08fea
Revises: e8078adc1215
Create Date: 2020-04-13 16:50:25.177040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e841d2e08fea'
down_revision = 'e8078adc1215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.create_foreign_key('user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('user')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('hobby', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###
